#ifndef PIRFIDREADER_GLOBAL_H
#define PIRFIDREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIRFIDREADER_LIBRARY)
#  define PIRFIDREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIRFIDREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIRFIDREADER_GLOBAL_H
