#ifndef PIIMAGEREADER_GLOBAL_H
#define PIIMAGEREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIIMAGEREADER_LIBRARY)
#  define PIIMAGEREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIIMAGEREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIIMAGEREADER_GLOBAL_H
