#ifndef PIGUIDEREADER_GLOBAL_H
#define PIGUIDEREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIGUIDEREADER_LIBRARY)
#  define PIGUIDEREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIGUIDEREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIGUIDEREADER_GLOBAL_H
