#ifndef PIDIGITALBOARD_GLOBAL_H
#define PIDIGITALBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIDIGITALBOARD_LIBRARY)
#  define PIDIGITALBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIDIGITALBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIDIGITALBOARD_GLOBAL_H
