#ifndef PIAGVMOTION_GLOBAL_H
#define PIAGVMOTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIAGVMOTION_LIBRARY)
#  define PIAGVMOTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIAGVMOTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIAGVMOTION_GLOBAL_H
