#ifndef PILIDARREADER_GLOBAL_H
#define PILIDARREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PILIDARREADER_LIBRARY)
#  define PILIDARREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PILIDARREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PILIDARREADER_GLOBAL_H
