#ifndef PILIDARRULE_GLOBAL_H
#define PILIDARRULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PILIDARRULE_LIBRARY)
#  define PILIDARRULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PILIDARRULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PILIDARRULE_GLOBAL_H
