#ifndef PIGYROREADER_GLOBAL_H
#define PIGYROREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PIGYROREADER_LIBRARY)
#  define PIGYROREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PIGYROREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PIGYROREADER_GLOBAL_H
